import {colors, typography} from '@core/styles';
import {DefaultTheme} from 'styled-components';

const theme: DefaultTheme = {
  space: {
    none: 0,
    xs: 2,
    sm: 4,
    md: 8,
    md2: 10,
    lg: 16,
    lg2: 18,
    lg3: 20,
    lg4: 22,
    lg5: 24,
    xl: 32,
    xl2: 34,
    xl3: 36,
    xl4: 38,
    xl5: 40,
  },
  colors: {
    transparent: colors.TRANSPARENT,
    primary: colors.PRIMARY,
    secondary: colors.SECONDARY,
    black: colors.BLACK,
    black2: colors.BLACK_2,
    gray: colors.GRAY,
    white: colors.WHITE,
    success: colors.SUCCESS,
    backgroundColor: colors.BACKGROUND_COLOR,
    lightBlue: colors.LIGHT_BLUE,
    lightGray: colors.LIGHT_GRAY,
    lightGray2: colors.LIGHT_GRAY_2,
    lightGreen: colors.LIGHT_GREEN,
    lightGreen2: colors.LIGHT_GREEN_2,
  },
  typography: {
    // FONT_REGULAR: typography.FONT_FAMILY_REGULAR,
    // FONT_BOLD: typography.FONT_FAMILY_BOLD,
  },
  borderWidths: {none: 0, xs: 2, sm: 4, md: 8, lg: 16, xl: 32, xxl: 64},
  bordersColors: {
    primary: colors.PRIMARY,
    secondary: colors.SECONDARY,
    black: colors.BLACK,
    white: colors.WHITE,
    success: colors.SUCCESS,
  },
  radii: {
    none: 0,
    xs: 2,
    sm: 4,
    md: 8,
    md2: 10,
    md3: 12,
    lg: 16,
    xl: 32,
    xxl: 64,
  },
  fontSizes: {
    none: 0,
    xs: 2,
    sm: 4,
    md: 8,
    md2: 10,
    md3: 12,
    md32: 13,
    md4: 14,
    lg: 16,
    lg2: 18,
    lg3: 20,
    xl: 32,
  },
  fonts: {
    primaryRegular: typography.PRIMARY_FONT_FAMILY_REGULAR,
    primaryBold: typography.PRIMARY_FONT_FAMILY_BOLD, // 700
    primarySemiBold: typography.PRIMARY_FONT_FAMILY_SEMI_BOLD, // 600
    secondaryRegular: typography.SECONDARY_FONT_FAMILY_REGULAR, // 400
    // body: typography.FONT_FAMILY_REGULAR,
    // heading: typography.FONT_FAMILY_BOLD,
  },
  letterSpacings: {
    normal: '-0.3px',
  },
  fontStyle: {
    normal: 'normal',
    italic: 'italic',
  },
  lineHeights: {
    none: 0,
    xs: 2,
    sm: 4,
    md: 8,
    lg: 16,
    lg2: 16,
    lg3: 18,
    lg4: 20,
    lg5: 22,
    lg6: 24,
    xl: 32,
  },
  fontWeights: {
    hairline: 100,
    thin: 200,
    light: 300,
    normal: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    extrabold: 800,
    black: 900,
    extraBlack: 950,
  },
};

export {theme};
